name: Deploy to GitHub Pages

on:
  workflow_dispatch: # 手動実行を許可

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: "app/package-lock.json"

      - name: Install dependencies
        run: |
          cd app
          npm ci

      - name: Run linter
        run: |
          cd app
          npm run lint

      - name: Run tests
        run: |
          cd app
          npm run test -- --run

      - name: Build application
        run: |
          cd app
          npm run build

      - name: Copy data files
        run: |
          cp -r data app/dist/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./app/dist"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
